In [148]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from collections import Counter

In [149]:
data = pd.read_csv('data.csv')
data.head(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015

In [150]:
len(data)

1890

# Предобработка датасета

In [151]:
answer_ls = [] # создадим список с ответами. сюда будем добавлять ответы по мере прохождения теста
# сюда можем вписать создание новых колонок в датасете

In [152]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 16 columns):
imdb_id                 1890 non-null object
popularity              1890 non-null float64
budget                  1890 non-null int64
revenue                 1890 non-null int64
original_title          1890 non-null object
cast                    1890 non-null object
director                1890 non-null object
tagline                 1890 non-null object
overview                1890 non-null object
runtime                 1890 non-null int64
genres                  1890 non-null object
production_companies    1890 non-null object
release_date            1890 non-null object
vote_count              1890 non-null int64
vote_average            1890 non-null float64
release_year            1890 non-null int64
dtypes: float64(2), int64(5), object(9)
memory usage: 236.4+ KB

# 1. У какого фильма из списка самый большой бюджет?
Варианты ответов:
1. The Dark Knight Rises (tt1345836)
2. Spider-Man 3 (tt0413300)
3. Avengers: Age of Ultron (tt2395427)
4. The Warrior's Way	(tt1032751)
5. Pirates of the Caribbean: On Stranger Tides (tt1298650)

In [153]:
# тут вводим ваш ответ и добавлем в него список ответов (сейчас для примера стоит "1")
a1=data[data.budget==data.budget.max()]
a1

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
491,tt1032751,0.25054,425000000,11087569,The Warrior's Way,Kate Bosworth|Jang Dong-gun|Geoffrey Rush|Dann...,Sngmoo Lee,Assassin. Hero. Legend.,An Asian assassin (Dong-gun Jang) is forced to...,100,Adventure|Fantasy|Action|Western|Thriller,Boram Entertainment Inc.,12/2/2010,74,6.4,2010

In [154]:
answer_ls.append('The Warrior\'s Way (tt1032751)')

# 2. Какой из фильмов самый длительный (в минутах)
1. The Lord of the Rings: The Return of the King	(tt0167260)
2. Gods and Generals	(tt0279111)
3. King Kong	(tt0360717)
4. Pearl Harbor	(tt0213149)
5. Alexander	(tt0346491)

In [155]:
a2=data[data.runtime==data.runtime.max()]
a2

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
1158,tt0279111,0.469518,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,23,5.8,2003

In [156]:
answer_ls.append('Gods and Generals (tt0279111)')

# 3. Какой из фильмов самый короткий (в минутах)
Варианты ответов:

1. Home on the Range	tt0299172
2. The Jungle Book 2	tt0283426
3. Winnie the Pooh	tt1449283
4. Corpse Bride	tt0121164
5. Hoodwinked!	tt0443536

In [157]:
a3=data[data.runtime==data.runtime.min()]
a3

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
769,tt1449283,1.425344,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,174,6.8,2011

In [158]:
answer_ls.append('Winnie the Pooh tt1449283')

# 4. Средняя длительность фильма?

Варианты ответов:
1. 115
2. 110
3. 105
4. 120
5. 100

In [159]:
a4=data['runtime'].mean()
a4

109.65343915343915

In [160]:
answer_ls.append(110)
answer_ls

["The Warrior's Way (tt1032751)",
 'Gods and Generals (tt0279111)',
 'Winnie the Pooh tt1449283',
 110]

# 5. Средняя длительность фильма по медиане?
Варианты ответов:
1. 106
2. 112
3. 101
4. 120
5. 115

In [161]:
a5=data['runtime'].median()
a5

106.5

In [162]:
answer_ls.append(106)
answer_ls

["The Warrior's Way (tt1032751)",
 'Gods and Generals (tt0279111)',
 'Winnie the Pooh tt1449283',
 110,
 106]

# 6. Какой самый прибыльный фильм?
Варианты ответов:
1. The Avengers	tt0848228
2. Minions	tt2293640
3. Star Wars: The Force Awakens	tt2488496
4. Furious 7	tt2820852
5. Avatar	tt0499549

In [163]:
a6=data[data.revenue==data.revenue.max()]
a6

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
239,tt0499549,9.432768,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,8458,7.1,2009

In [164]:
answer_ls.append('Avatar tt0499549')

# 7. Какой фильм самый убыточный?
Варианты ответов:
1. Supernova tt0134983
2. The Warrior's Way tt1032751
3. Flushed Away	tt0424095
4. The Adventures of Pluto Nash	tt0180052
5. The Lone Ranger	tt1210819

In [165]:
a7=data[data.revenue==data.revenue.min()]#####???????????????????????????????????????The Adventures of Pluto Nash tt0180052
a7

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
713,tt0490181,0.32288,8000000,2033165,Mutant Chronicles,Ron Perlman|Thomas Jane|Devon Aoki|Sean Pertwe...,Simon Hunter,Welcome to the 23rd century. The new dark ages.,It's the year 2707. Earth's natural resources ...,111,Action|Adventure|Horror|Science Fiction,Isle of Man Film|Edward R. Pressman Film|Parad...,8/7/2008,61,5.1,2008

In [166]:
answer_ls.append('The Adventures of Pluto Nash tt0180052')

# 8. Сколько всего фильмов в прибыли?
Варианты ответов:
1. 1478
2. 1520
3. 1241
4. 1135
5. 1398

In [167]:
a8=data[data.revenue>data.budget].count()
a8

imdb_id                 1478
popularity              1478
budget                  1478
revenue                 1478
original_title          1478
cast                    1478
director                1478
tagline                 1478
overview                1478
runtime                 1478
genres                  1478
production_companies    1478
release_date            1478
vote_count              1478
vote_average            1478
release_year            1478
dtype: int64

In [168]:
answer_ls.append(1478)

# 9. Самый прибыльный фильм в 2008 году?
Варианты ответов:
1. Madagascar: Escape 2 Africa	tt0479952
2. Iron Man	tt0371746
3. Kung Fu Panda	tt0441773
4. The Dark Knight	tt0468569
5. Mamma Mia!	tt0795421

In [169]:
a9=data[data.release_date.str.contains('2008')]
a9

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
600,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8432,8.1,2008
601,tt0910970,5.678119,180000000,521311860,WALLÂ·E,Ben Burtt|Elissa Knight|Jeff Garlin|Fred Willa...,Andrew Stanton,An adventure beyond the ordinar-E.,WALLÂ·E is the last robot left on an Earth tha...,98,Animation|Family,Walt Disney Pictures|Pixar Animation Studios,6/22/2008,4209,7.6,2008
602,tt0371746,4.977955,140000000,585174222,Iron Man,Robert Downey Jr.|Terrence Howard|Jeff Bridges...,Jon Favreau,Heroes aren't born. They're built.,"After being held captive in an Afghan cave, bi...",126,Action|Science Fiction|Adventure,Marvel Studios,4/30/2008,6220,7.3,2008
603,tt0936501,3.647612,25000000,226830568,Taken,Liam Neeson|Famke Janssen|Maggie Grace|Katie C...,Pierre Morel,They took his daughter. He'll take their lives.,"While vacationing with a friend in Paris, an A...",93,Action|Thriller|Crime,Twentieth Century Fox Film Corporation|M6 Film...,2/18/2008,3075,7.2,2008
604,tt0367882,3.161670,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,1537,5.6,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,tt0858479,0.278543,7000000,10569964,Smart People,Dennis Quaid|Sarah Jessica Parker|Ellen Page|T...,Noam Murro,Sometimes the smartest people have the most to...,Professor Lawrence Wetherhold (Dennis Quaid) m...,95,Comedy|Drama|Romance,Miramax Films|Sherazade Film Development|Groun...,4/11/2008,34,5.5,2008
717,tt0410377,0.768409,37000000,100076342,Nim's Island,Abigail Breslin|Jodie Foster|Gerard Butler|Mic...,Jennifer Flackett|Mark Levin,Your adventure starts here.,A young girl inhabits an isolated island with ...,96,Adventure|Comedy|Family|Fantasy,Walden Media,4/3/2008,183,5.5,2008
718,tt0465502,0.259988,25000000,30000000,Igor,John Cusack|Myleene Klass|Robin Walsh|Matt McK...,Anthony Leondis,All men aren't created Evil.,Animated fable about a clichÃ© hunchbacked evi...,87,Animation|Comedy|Family|Fantasy,Exodus Film Group|Exodus Productions,9/19/2008,89,5.4,2008
719,tt0455538,0.659884,27000000,17286299,How to Lose Friends & Alienate People,Kelan Pannell|Janette Scott|Simon Pegg|Megan F...,Robert B. Weide,"He's across the pond, and out of his depth.",A British writer struggles to fit in at a high...,110,Comedy|Romance|Drama,UK Film Council|Intandem Films|Aramid Entertai...,10/2/2008,106,6.0,2008
720,tt0494652,0.224471,35000000,43650785,Welcome Home Roscoe Jenkins,Martin Lawrence|James Earl Jones|Margaret Aver...,Malcolm D. Lee,Roscoe Jenkins aims for the heartstrings and f...,"Martin Lawrence leads an all-star cast, includ...",114,Comedy|Drama,Universal Pictures|Spyglass Entertainment,2/8/2008,31,6.1,2008

In [170]:
answer_ls.append('The Dark Knight tt0468569')

# 10. Самый убыточный фильм за период с 2012 по 2014 (включительно)?
Варианты ответов:
1. Winter's Tale	tt1837709
2. Stolen	tt1656186
3. Broken City	tt1235522
4. Upside Down	tt1374992
5. The Lone Ranger	tt1210819

In [171]:
a9=data[data.release_date.str.contains('2012')]
a9

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
971,tt0848228,7.637767,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,8903,7.3,2012
972,tt1496025,7.031452,70000000,132400000,Underworld: Awakening,Kate Beckinsale|Stephen Rea|Michael Ealy|Theo ...,MÃ¥ns MÃ¥rlind|BjÃ¶rn Stein,Vengeance Returns,After being held in a coma-like state for fift...,88,Fantasy|Action|Horror,Lakeshore Entertainment|Saturn Films|Screen Ge...,1/19/2012,1426,6.0,2012
973,tt1345836,6.591277,250000000,1081041287,The Dark Knight Rises,Christian Bale|Michael Caine|Gary Oldman|Anne ...,Christopher Nolan,The Legend Ends,Following the death of District Attorney Harve...,165,Action|Crime|Drama|Thriller,Legendary Pictures|Warner Bros.|DC Entertainme...,7/16/2012,6723,7.5,2012
974,tt1853728,5.944518,100000000,425368238,Django Unchained,Jamie Foxx|Christoph Waltz|Leonardo DiCaprio|K...,Quentin Tarantino,"Life, liberty and the pursuit of vengeance.","With the help of a German bounty hunter, a fre...",165,Drama|Western,Columbia Pictures|The Weinstein Company,12/25/2012,7375,7.7,2012
975,tt1074638,5.603587,200000000,1108561013,Skyfall,Daniel Craig|Judi Dench|Javier Bardem|Ralph Fi...,Sam Mendes,Think on your sins.,When Bond's latest assignment goes gravely wro...,143,Action|Adventure|Thriller,Columbia Pictures,10/25/2012,6137,6.8,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,tt1433822,0.398497,17000000,9627492,The Apparition,Ashley Greene|Sebastian Stan|Tom Felton|Julian...,Todd Lincoln,Once You Believe You Die,Plagued by frightening occurrences in their ho...,82,Horror|Thriller,StudioCanal|Dark Castle Entertainment|Warner B...,8/23/2012,76,4.4,2012
1078,tt1480656,0.359578,20500000,6063556,Cosmopolis,Robert Pattinson|Sarah Gadon|Juliette Binoche|...,David Cronenberg,How far can he go before he goes too far?,Riding across Manhattan in a stretch limo in o...,109,Drama,France 2 CinÃ©ma|TÃ©lÃ©film Canada|Rai Cinema|...,5/25/2012,191,4.8,2012
1079,tt1855325,0.260624,65000000,240159255,Resident Evil: Retribution,Milla Jovovich|Sienna Guillory|Michelle Rodrig...,Paul W.S. Anderson,The Ultimate Battle Begins,The Umbrella Corporationâ€™s deadly T-virus co...,95,Action|Horror|Science Fiction,Davis-Films,9/12/2012,1152,5.6,2012
1080,tt1876451,0.308684,14000000,24637469,Sparkle,Whitney Houston|Cee Lo Green|Derek Luke|Mike E...,Salim Akil,Celebrate the legend.,"Musical prodigy, Sparkle (Jordin Sparks) strug...",116,Drama|Music,TriStar Pictures|Phoenix Pictures|Stage 6 Film...,8/17/2012,21,5.9,2012
1081,tt2215719,0.050524,12000000,32726956,Katy Perry: Part of Me,Katy Perry|Russell Brand|Shannon Woodward|Rach...,Dan Cutforth|Jane Lipsitz,Be yourself and you can be anything,Giving fans unprecedented access to the real l...,93,Documentary|Music,Paramount Pictures|Imagine Entertainment|MTV F...,6/28/2012,63,6.5,2012

In [172]:
answer_ls.append('Stolen tt1656186')

# 11. Какого жанра фильмов больше всего?
Варианты ответов:
1. Action
2. Adventure
3. Drama
4. Comedy
5. Thriller

In [173]:
action_cnt=data[data.genres.str.contains('Thriller')].count()
action_cnt

imdb_id                 597
popularity              597
budget                  597
revenue                 597
original_title          597
cast                    597
director                597
tagline                 597
overview                597
runtime                 597
genres                  597
production_companies    597
release_date            597
vote_count              597
vote_average            597
release_year            597
dtype: int64

In [174]:
answer_ls.append('Drama')

# 12. Какого жанра среди прибыльных фильмов больше всего?
Варианты ответов:
1. Drama
2. Comedy
3. Action
4. Thriller
5. Adventure

In [175]:
a12=data[data.revenue>data.budget]
cnt=a12[a12.genres.str.contains('Adventure')].count()
cnt

imdb_id                 337
popularity              337
budget                  337
revenue                 337
original_title          337
cast                    337
director                337
tagline                 337
overview                337
runtime                 337
genres                  337
production_companies    337
release_date            337
vote_count              337
vote_average            337
release_year            337
dtype: int64

In [176]:
answer_ls.append('Drama')

# 13. Кто из режиссеров снял больше всего фильмов?
Варианты ответов:
1. Steven Spielberg
2. Ridley Scott 
3. Steven Soderbergh
4. Christopher Nolan
5. Clint Eastwood

In [177]:
ss=data[data.director=='Steven Soderbergh'].count()
ss

imdb_id                 13
popularity              13
budget                  13
revenue                 13
original_title          13
cast                    13
director                13
tagline                 13
overview                13
runtime                 13
genres                  13
production_companies    13
release_date            13
vote_count              13
vote_average            13
release_year            13
dtype: int64

In [178]:
answer_ls.append('Steven Soderbergh')

# 14. Кто из режиссеров снял больше всего Прибыльных фильмов?
Варианты ответов:
1. Steven Soderbergh
2. Clint Eastwood
3. Steven Spielberg
4. Ridley Scott
5. Christopher Nolan

In [179]:
a14=data[data.revenue>data.budget]
cnt_dirs=a14[a14.director=='Christopher Nolan'].count()
cnt_dirs

imdb_id                 8
popularity              8
budget                  8
revenue                 8
original_title          8
cast                    8
director                8
tagline                 8
overview                8
runtime                 8
genres                  8
production_companies    8
release_date            8
vote_count              8
vote_average            8
release_year            8
dtype: int64

In [180]:
answer_ls.append('Ridley Scott')

# 15. Кто из режиссеров принес больше всего прибыли?
Варианты ответов:
1. Steven Spielberg
2. Christopher Nolan
3. David Yates
4. James Cameron
5. Peter Jackson

In [181]:
data[data.director=='Steven Spielberg']['revenue'].max()

786636033

In [182]:
answer_ls.append('James Cameron')

# 16. Какой актер принес больше всего прибыли?
Варианты ответов:
1. Emma Watson
2. Johnny Depp
3. Michelle Rodriguez
4. Orlando Bloom
5. Rupert Grint

In [183]:
answer_ls.append('Johnny Depp')

# 17. Какой актер принес меньше всего прибыли в 2012 году?
Варианты ответов:
1. Nicolas Cage
2. Danny Huston
3. Kirsten Dunst
4. Jim Sturgess
5. Sami Gayle

In [184]:
movies_2012=data[data.release_year==2012].sort_values('revenue', ascending=True)
movies_2012

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
1034,tt1656186,1.157127,35000000,2106557,Stolen,Nicolas Cage|Malin Ã…kerman|Josh Lucas|Sami Ga...,Simon West,Never steal from the world's greatest thief.,A former thief frantically searches for his mi...,96,Action|Crime|Drama|Thriller,Saturn Films|Nu Image Films|Millennium Films,5/17/2012,233,5.1,2012
1049,tt1433811,0.903283,10000000,3428048,Disconnect,Jason Bateman|Hope Davis|Frank Grillo|Paula Pa...,Henry Alex Rubin,Look up.,Disconnect interweaves multiple storylines abo...,115,Drama|Thriller,Lionsgate|Liddell Entertainment|LD Entertainme...,9/11/2012,302,6.7,2012
1076,tt1925431,0.409718,20000000,4636169,Fire with Fire,Bruce Willis|Josh Duhamel|Rosario Dawson|Vince...,David Barrett,Revenge has its own set of rules.,A fireman takes an unexpected course of action...,97,Action|Crime|Drama|Thriller,Industry Entertainment|Grindstone Entertainmen...,8/31/2012,144,5.7,2012
1078,tt1480656,0.359578,20500000,6063556,Cosmopolis,Robert Pattinson|Sarah Gadon|Juliette Binoche|...,David Cronenberg,How far can he go before he goes too far?,Riding across Manhattan in a stretch limo in o...,109,Drama,France 2 CinÃ©ma|TÃ©lÃ©film Canada|Rai Cinema|...,5/25/2012,191,4.8,2012
1008,tt1374992,1.690572,60000000,8106475,Upside Down,Kirsten Dunst|Jim Sturgess|Timothy Spall|James...,Juan Diego Solanas,Two worlds. One future.,In an alternate universe where twinned worlds ...,104,Romance|Science Fiction|Drama|Fantasy,Onyx Films|Studio 37|Jouror Productions|France...,9/27/2012,695,6.1,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,tt1667889,3.135776,95000000,877244782,Ice Age: Continental Drift,John Leguizamo|Ray Romano|Chris Wedge|Denis Le...,Steve Martino|Mike Thurmeier,"Manny, Diego, and Sid embark upon another adve...","Manny, Diego, and Sid embark upon another adve...",88,Animation|Comedy|Adventure|Family,Blue Sky Studios|Twentieth Century Fox Animation,6/26/2012,1920,6.2,2012
977,tt0903624,4.218933,250000000,1017003568,The Hobbit: An Unexpected Journey,Ian McKellen|Martin Freeman|Richard Armitage|A...,Peter Jackson,From the smallest beginnings come the greatest...,"Bilbo Baggins, a hobbit enjoying his quiet lif...",169,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|Metro-Goldwyn-Ma...,11/26/2012,6417,6.9,2012
973,tt1345836,6.591277,250000000,1081041287,The Dark Knight Rises,Christian Bale|Michael Caine|Gary Oldman|Anne ...,Christopher Nolan,The Legend Ends,Following the death of District Attorney Harve...,165,Action|Crime|Drama|Thriller,Legendary Pictures|Warner Bros.|DC Entertainme...,7/16/2012,6723,7.5,2012
975,tt1074638,5.603587,200000000,1108561013,Skyfall,Daniel Craig|Judi Dench|Javier Bardem|Ralph Fi...,Sam Mendes,Think on your sins.,When Bond's latest assignment goes gravely wro...,143,Action|Adventure|Thriller,Columbia Pictures,10/25/2012,6137,6.8,2012
971,tt0848228,7.637767,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,8903,7.3,2012

In [185]:
answer_ls.append('Nicolas Cage')

# 18. Какой актер снялся в большем количестве высокобюджетных фильмов? (в фильмах где бюджет выше среднего по данной выборке)
Варианты ответов:
1. Tom Cruise
2. Mark Wahlberg 
3. Matt Damon
4. Angelina Jolie
5. Adam Sandler

In [186]:
av_budget=data.budget.mean()
av_budget

54506961.474603176

In [187]:
above_budget=data[data.budget>data.budget.mean()]['cast']
cnt_TC=0
for i in above_budget:
    if 'Matt Damon' in i:
        cnt_TC+=1
cnt_TC

18

In [188]:
answer_ls.append('Matt Damon')

# 19. В фильмах какого жанра больше всего снимался Nicolas Cage?  
Варианты ответа:
1. Drama
2. Action
3. Thriller
4. Adventure
5. Crime

In [189]:
nc_m=data[data.cast.str.contains('Nicolas Cage')]
gnr=['Drama', 'Action','Thriller', 'Adventure', 'Crime']
nc_m[nc_m.genres.str.contains("Action")].count()

imdb_id                 17
popularity              17
budget                  17
revenue                 17
original_title          17
cast                    17
director                17
tagline                 17
overview                17
runtime                 17
genres                  17
production_companies    17
release_date            17
vote_count              17
vote_average            17
release_year            17
dtype: int64

In [190]:
answer_ls.append('Action')

# 20. Какая студия сняла больше всего фильмов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [191]:
a20=data[data.production_companies.str.contains('Universal Pictures')].count()
a20

imdb_id                 175
popularity              175
budget                  175
revenue                 175
original_title          175
cast                    175
director                175
tagline                 175
overview                175
runtime                 175
genres                  175
production_companies    175
release_date            175
vote_count              175
vote_average            175
release_year            175
dtype: int64

In [192]:
answer_ls.append('Universal Pictures')

# 21. Какая студия сняла больше всего фильмов в 2015 году?
Варианты ответа:
1. Universal Pictures
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [193]:
a21=data[(data.release_year==2015) & (data.production_companies.str.contains('Universal Pictures'))].count()
a21

imdb_id                 11
popularity              11
budget                  11
revenue                 11
original_title          11
cast                    11
director                11
tagline                 11
overview                11
runtime                 11
genres                  11
production_companies    11
release_date            11
vote_count              11
vote_average            11
release_year            11
dtype: int64

In [194]:
answer_ls.append('Universal Pictures')

# 22. Какая студия заработала больше всего денег в жанре комедий за все время?
Варианты ответа:
1. Warner Bros
2. Universal Pictures (Universal)
3. Columbia Pictures
4. Paramount Pictures
5. Walt Disney

In [195]:
a22=data[(data.genres.str.contains('Comedy'))&(data.production_companies.str.contains('Disney'))].count()
a22

imdb_id                 47
popularity              47
budget                  47
revenue                 47
original_title          47
cast                    47
director                47
tagline                 47
overview                47
runtime                 47
genres                  47
production_companies    47
release_date            47
vote_count              47
vote_average            47
release_year            47
dtype: int64

In [196]:
answer_ls.append('Columbia Pictures')

# 23. Какая студия заработала больше всего денег в 2012 году?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Columbia Pictures
4. Paramount Pictures
5. Lucasfilm

In [197]:
companies=['Universal','Warner Bros','Columbia','Paramount','Lucasfilm']
for comp in companies:
    rev_2012=data[(data.release_year==2012)&(data.production_companies.str.contains(comp))]['revenue'].sum()
    print(rev_2012)

2901011579
1869520056
3468406608
606726715
50365377

In [198]:
answer_ls.append('Columbia Pictures')

# 24. Самый убыточный фильм от Paramount Pictures
Варианты ответа:

1. K-19: The Widowmaker tt0267626
2. Next tt0435705
3. Twisted tt0315297
4. The Love Guru tt0811138
5. The Fighter tt0964517

In [199]:
data[data.production_companies.str.contains('Paramount Pictures')].sort_values('revenue', ascending=True)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
436,tt0964517,1.054685,25000000,9190869,The Fighter,Mark Wahlberg|Christian Bale|Amy Adams|Melissa...,David O. Russell,Every dream deserves a fighting chance.,"The Fighter, is a drama about boxer ""Irish"" Mi...",116,Drama,Paramount Pictures,12/17/2010,965,7.1,2010
960,tt0267248,0.246694,25000000,10719357,Abandon,Katie Holmes|Benjamin Bratt|Charlie Hunnam|Zoo...,Stephen Gaghan,Watch who you leave behind.,A psychological thriller about a senior at one...,99,Drama|Mystery|Thriller,Paramount Pictures|Spyglass Entertainment|Touc...,10/14/2002,20,4.9,2002
1069,tt1663143,0.615971,14000000,11417362,Fun Size,Victoria Justice|Jackson Nicoll|Chelsea Handle...,Josh Schwartz,Some people just can't handle Halloween.,Wren (Victoria Justice) is invited to a Hallow...,87,Comedy,Paramount Pictures|Nickelodeon Movies|Anonymou...,10/25/2012,83,5.4,2012
1391,tt0384680,0.707056,20000000,12482775,The Weather Man,Nicolas Cage|Michael Caine|Hope Davis|Gemmenne...,Gore Verbinski,Dave Spritz is about to take his best shot . ....,"A Chicago weather man, separated from his wife...",101,Comedy|Drama,Paramount Pictures|Escape Artists|Kumar Mobili...,10/20/2005,147,5.7,2005
1661,tt0324127,0.308525,27000000,13000000,Suspect Zero,Carrie-Anne Moss|Aaron Eckhart|Ben Kingsley|Ha...,E. Elias Merhige,Who's next?,"A killer is on the loose, and an FBI agent sif...",99,Crime|Thriller,Paramount Pictures|Cruise/Wagner Productions|L...,8/27/2004,42,5.1,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,tt1229238,2.952740,145000000,694713380,Mission: Impossible - Ghost Protocol,Tom Cruise|Jeremy Renner|Simon Pegg|Paula Patt...,Brad Bird,No Plan. No Backup. No Choice.,In the 4th installment of the Mission Impossib...,133,Action|Thriller|Adventure,Paramount Pictures|Skydance Productions|Bad Ro...,12/7/2011,3036,6.7,2011
1739,tt0418279,0.890557,150000000,709709780,Transformers,Shia LaBeouf|Josh Duhamel|Megan Fox|Rachael Ta...,Michael Bay,Their war. Our world.,"Young teenager, Sam Witwicky becomes involved ...",144,Adventure|Science Fiction|Action,Paramount Pictures|DreamWorks SKG|Amblin Enter...,6/27/2007,2752,6.6,2007
604,tt0367882,3.161670,185000000,786636033,Indiana Jones and the Kingdom of the Crystal S...,Harrison Ford|Cate Blanchett|Shia LaBeouf|Ray ...,Steven Spielberg,The adventure continues . . .,"Set during the Cold War, the Soviets â€“ led b...",122,Adventure|Action,Lucasfilm|Paramount Pictures,5/21/2008,1537,5.6,2008
317,tt1055369,0.813323,150000000,836297228,Transformers: Revenge of the Fallen,Shia LaBeouf|Megan Fox|Josh Duhamel|Rainn Wils...,Michael Bay,Revenge is coming,Sam Witwicky leaves the Autobots behind for a ...,150,Science Fiction|Action|Adventure,Paramount Pictures|DreamWorks SKG|Amblin Enter...,6/19/2009,2230,6.0,2009
829,tt1399103,0.760503,195000000,1123746996,Transformers: Dark of the Moon,Shia LaBeouf|John Malkovich|Ken Jeong|Frances ...,Michael Bay,The invasion we always feared. An enemy we nev...,Sam Witwicky takes his first tenuous steps int...,154,Action|Science Fiction|Adventure,Paramount Pictures|Di Bonaventura Pictures|Has...,6/28/2011,2456,6.1,2011

In [200]:
answer_ls.append('The Fighter tt0964517')

# 25. Какой Самый прибыльный год (заработали больше всего)?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2002
5. 2015

In [201]:
data.groupby(['release_year'])['revenue'].sum()

release_year
2000    10664099805
2001    13017764865
2002    14136361487
2003    14346123312
2004    15663430720
2005    15309425558
2006    14775042320
2007    18162406801
2008    18252781990
2009    20261791024
2010    21082292530
2011    22676791872
2012    23079001687
2013    23213799791
2014    23405862953
2015    25449202382
Name: revenue, dtype: int64

In [202]:
answer_ls.append(2015)

# 26. Какой Самый прибыльный год для студии Warner Bros?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2010
5. 2015

In [203]:
wb=data[data.production_companies.str.contains('Warner Bros')]
wb.groupby(['release_year'])['revenue'].sum().sort_values(ascending=False)
#wb.groupby('release_year')

release_year
2014    3243064519
2007    3183675217
2008    3050595031
2010    3008712985
2011    2845393682
2003    2745493377
2009    2737954136
2004    2731933725
2013    2599953400
2005    2412980298
2001    2266545668
2012    1869520056
2002    1702709901
2015    1691168351
2006    1521170743
2000    1025531386
Name: revenue, dtype: int64

In [204]:
answer_ls.append(2014)

# 27. В каком месяце за все годы суммарно вышло больше всего фильмов?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [205]:
data[data.release_date.str.startswith('5/')].count()

imdb_id                 140
popularity              140
budget                  140
revenue                 140
original_title          140
cast                    140
director                140
tagline                 140
overview                140
runtime                 140
genres                  140
production_companies    140
release_date            140
vote_count              140
vote_average            140
release_year            140
dtype: int64

In [206]:
answer_ls.append('Сентябрь')

# 28. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)
Варианты ответа:
1. 345
2. 450
3. 478
4. 523
5. 381

In [207]:
mo=['6/','7/','8/']
cnt_mo=0
for m in mo:
    cnt_mo+=data[data.release_date.str.startswith(m)].count()
    print(cnt_mo)

imdb_id                 147
popularity              147
budget                  147
revenue                 147
original_title          147
cast                    147
director                147
tagline                 147
overview                147
runtime                 147
genres                  147
production_companies    147
release_date            147
vote_count              147
vote_average            147
release_year            147
dtype: int64
imdb_id                 289
popularity              289
budget                  289
revenue                 289
original_title          289
cast                    289
director                289
tagline                 289
overview                289
runtime                 289
genres                  289
production_companies    289
release_date            289
vote_count              289
vote_average            289
release_year            289
dtype: int64
imdb_id                 450
popularity              450
budget                  450
revenue                 450
original_title          450
cast                    450
director                450
tagline                 450
overview                450
runtime                 450
genres                  450
production_companies    450
release_date            450
vote_count              450
vote_average            450
release_year            450
dtype: int64

In [208]:
answer_ls.append(450)

# 29. Какой режисер выпускает (суммарно по годам) больше всего фильмов зимой?
Варианты ответов:
1. Steven Soderbergh
2. Christopher Nolan
3. Clint Eastwood
4. Ridley Scott
5. Peter Jackson

In [209]:
dir_movies=data[(data.director=='Peter Jackson')&(data.release_date.str.startswith('1/'))].count()
dir_movies

imdb_id                 0
popularity              0
budget                  0
revenue                 0
original_title          0
cast                    0
director                0
tagline                 0
overview                0
runtime                 0
genres                  0
production_companies    0
release_date            0
vote_count              0
vote_average            0
release_year            0
dtype: int64

In [210]:
answer_ls.append('Peter Jackson')

# 30. Какой месяц чаще всего по годам самый прибыльный?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [211]:
a30=data[data.release_date.str.startswith('12/')].groupby(['release_year'])
a30.revenue.sum().mean()

2424116967.125

In [212]:
answer_ls.append('Декабрь')

# 31. Названия фильмов какой студии в среднем самые длинные по количеству символов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [213]:
data[data.production_companies.str.contains('Four By Two Productions')]['original_title'].str.len().sum()

83

In [214]:
answer_ls.append('Four By Two Productions')

# 32. Названия фильмов какой студии в среднем самые длинные по количеству слов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [215]:
data[data.production_companies.str.contains('Four By Two Productions')]['original_title']

1449    Borat: Cultural Learnings of America for Make ...
Name: original_title, dtype: object

In [216]:
answer_ls.append('Four By Two Productions')

# 33. Сколько разных слов используется в названиях фильмов?(без учета регистра)
Варианты ответа:
1. 6540
2. 1002
3. 2461
4. 28304
5. 3432

In [217]:
data_words=[]
for i in data.original_title:
    i_low=i.lower()
    data_words.append(i_low.split())
data_words
d_w=[]
for k in data_words:
    for l in k:
        d_w.append(l)
len(set(d_w))

2461

In [218]:
answer_ls.append(2461)

# 34. Какие фильмы входят в 1 процент лучших по рейтингу?
Варианты ответа:
1. Inside Out, Gone Girl, 12 Years a Slave
2. BloodRayne, The Adventures of Rocky & Bullwinkle
3. The Lord of the Rings: The Return of the King
4. 300, Lucky Number Slevin

In [219]:
data[data.vote_average==data.vote_average.max()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
600,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8432,8.1,2008

In [220]:
data[data.original_title=='Lucky Number Slevin']

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
1457,tt0425210,1.520387,27000000,56308881,Lucky Number Slevin,Josh Hartnett|Bruce Willis|Lucy Liu|Morgan Fre...,Paul McGuigan,Wrong Time. Wrong Place. Wrong Number.,Slevin is mistakenly put in the middle of a pe...,110,Drama|Thriller|Crime|Mystery,The Weinstein Company|FilmEngine|Capitol Films...,2/24/2006,787,7.3,2006

In [221]:
answer_ls.append('Inside Out, Gone Girl, 12 Years a Slave')

# 35. Какие актеры чаще всего снимаются в одном фильме вместе
Варианты ответа:
1. Johnny Depp & Helena Bonham Carter
2. Hugh Jackman & Ian McKellen
3. Vin Diesel & Paul Walker
4. Adam Sandler & Kevin James
5. Daniel Radcliffe & Rupert Grint

In [222]:
a35=data[(data.cast.str.contains('Daniel Radcliffe'))&(data.cast.str.contains('Rupert Grint'))]
len(a35)

8

In [223]:
answer_ls.append('Daniel Radcliffe & Rupert Grint')

# 36. У какого из режиссеров выше вероятность выпустить фильм в прибыли? (5 баллов)101
Варианты ответа:
1. Quentin Tarantino
2. Steven Soderbergh
3. Robert Rodriguez
4. Christopher Nolan
5. Clint Eastwood

In [224]:
answer_ls.append('Christopher Nolan')

# Submission

In [225]:
len(answer_ls)

36

In [226]:
pd.DataFrame({'Id':range(1,len(answer_ls)+1), 'Answer':answer_ls}, columns=['Id', 'Answer'])

    Id                                   Answer
0    1            The Warrior's Way (tt1032751)
1    2            Gods and Generals (tt0279111)
2    3                Winnie the Pooh tt1449283
3    4                                      110
4    5                                      106
5    6                         Avatar tt0499549
6    7   The Adventures of Pluto Nash tt0180052
7    8                                     1478
8    9                The Dark Knight tt0468569
9   10                         Stolen tt1656186
10  11                                    Drama
11  12                                    Drama
12  13                        Steven Soderbergh
13  14                             Ridley Scott
14  15                            James Cameron
15  16                              Johnny Depp
16  17                             Nicolas Cage
17  18                               Matt Damon
18  19                                   Action
19  20                       Universal Pictures
20  21                       Universal Pictures
21  22                        Columbia Pictures
22  23                        Columbia Pictures
23  24                    The Fighter tt0964517
24  25                                     2015
25  26                                     2014
26  27                                 Сентябрь
27  28                                      450
28  29                            Peter Jackson
29  30                                  Декабрь
30  31                  Four By Two Productions
31  32                  Four By Two Productions
32  33                                     2461
33  34  Inside Out, Gone Girl, 12 Years a Slave
34  35          Daniel Radcliffe & Rupert Grint
35  36                        Christopher Nolan