In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from collections import Counter

In [3]:
data = pd.read_csv('data.csv')
data.head(5)

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015

In [4]:
len(data)

1890

# Предобработка датасета

In [5]:
answer_ls = [] # создадим список с ответами.

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 16 columns):
imdb_id                 1890 non-null object
popularity              1890 non-null float64
budget                  1890 non-null int64
revenue                 1890 non-null int64
original_title          1890 non-null object
cast                    1890 non-null object
director                1890 non-null object
tagline                 1890 non-null object
overview                1890 non-null object
runtime                 1890 non-null int64
genres                  1890 non-null object
production_companies    1890 non-null object
release_date            1890 non-null object
vote_count              1890 non-null int64
vote_average            1890 non-null float64
release_year            1890 non-null int64
dtypes: float64(2), int64(5), object(9)
memory usage: 236.4+ KB

# 1. У какого фильма из списка самый большой бюджет?
Варианты ответов:
1. The Dark Knight Rises (tt1345836)
2. Spider-Man 3 (tt0413300)
3. Avengers: Age of Ultron (tt2395427)
4. The Warrior's Way	(tt1032751)
5. Pirates of the Caribbean: On Stranger Tides (tt1298650)

In [7]:
# тут вводим ваш ответ и добавлем в него список ответов (сейчас для примера стоит "1")
data[data.budget==data.budget.max()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
491,tt1032751,0.25054,425000000,11087569,The Warrior's Way,Kate Bosworth|Jang Dong-gun|Geoffrey Rush|Dann...,Sngmoo Lee,Assassin. Hero. Legend.,An Asian assassin (Dong-gun Jang) is forced to...,100,Adventure|Fantasy|Action|Western|Thriller,Boram Entertainment Inc.,12/2/2010,74,6.4,2010

In [8]:
answer_ls.append('The Warrior\'s Way (tt1032751)')
answer_ls

["The Warrior's Way (tt1032751)"]

# 2. Какой из фильмов самый длительный (в минутах)
1. The Lord of the Rings: The Return of the King	(tt0167260)
2. Gods and Generals	(tt0279111)
3. King Kong	(tt0360717)
4. Pearl Harbor	(tt0213149)
5. Alexander	(tt0346491)

In [9]:
data[data.runtime==data.runtime.max()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
1158,tt0279111,0.469518,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,23,5.8,2003

In [10]:
answer_ls.append('Gods and Generals (tt0279111)')

# 3. Какой из фильмов самый короткий (в минутах)
Варианты ответов:

1. Home on the Range	tt0299172
2. The Jungle Book 2	tt0283426
3. Winnie the Pooh	tt1449283
4. Corpse Bride	tt0121164
5. Hoodwinked!	tt0443536

In [11]:
data[data.runtime==data.runtime.min()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
769,tt1449283,1.425344,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,174,6.8,2011

In [12]:
answer_ls.append('Winnie the Pooh tt1449283')

# 4. Средняя длительность фильма?

Варианты ответов:
1. 115
2. 110
3. 105
4. 120
5. 100

In [13]:
data['runtime'].mean()

109.65343915343915

In [14]:
answer_ls.append(110)
answer_ls

["The Warrior's Way (tt1032751)",
 'Gods and Generals (tt0279111)',
 'Winnie the Pooh tt1449283',
 110]

# 5. Средняя длительность фильма по медиане?
Варианты ответов:
1. 106
2. 112
3. 101
4. 120
5. 115

In [15]:
data['runtime'].median()

106.5

In [16]:
answer_ls.append(106)
answer_ls

["The Warrior's Way (tt1032751)",
 'Gods and Generals (tt0279111)',
 'Winnie the Pooh tt1449283',
 110,
 106]

# 6. Какой самый прибыльный фильм?
Варианты ответов:
1. The Avengers	tt0848228
2. Minions	tt2293640
3. Star Wars: The Force Awakens	tt2488496
4. Furious 7	tt2820852
5. Avatar	tt0499549

In [17]:
data[data.revenue==data.revenue.max()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
239,tt0499549,9.432768,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,8458,7.1,2009

In [18]:
answer_ls.append('Avatar tt0499549')
answer_ls

["The Warrior's Way (tt1032751)",
 'Gods and Generals (tt0279111)',
 'Winnie the Pooh tt1449283',
 110,
 106,
 'Avatar tt0499549']

# 7. Какой фильм самый убыточный?
Варианты ответов:
1. Supernova tt0134983
2. The Warrior's Way tt1032751
3. Flushed Away	tt0424095
4. The Adventures of Pluto Nash	tt0180052
5. The Lone Ranger	tt1210819

In [19]:
data['rev_budg']=data.apply(lambda row: row.revenue - 
                                  row.budget, axis = 1)
data[data.rev_budg==data.rev_budg.min()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,rev_budg
491,tt1032751,0.25054,425000000,11087569,The Warrior's Way,Kate Bosworth|Jang Dong-gun|Geoffrey Rush|Dann...,Sngmoo Lee,Assassin. Hero. Legend.,An Asian assassin (Dong-gun Jang) is forced to...,100,Adventure|Fantasy|Action|Western|Thriller,Boram Entertainment Inc.,12/2/2010,74,6.4,2010,-413912431

In [20]:
answer_ls.append('The Warrior\'s Way tt1032751')

# 8. Сколько всего фильмов в прибыли?
Варианты ответов:
1. 1478
2. 1520
3. 1241
4. 1135
5. 1398

In [21]:
data[data.revenue>data.budget].count()

imdb_id                 1478
popularity              1478
budget                  1478
revenue                 1478
original_title          1478
cast                    1478
director                1478
tagline                 1478
overview                1478
runtime                 1478
genres                  1478
production_companies    1478
release_date            1478
vote_count              1478
vote_average            1478
release_year            1478
rev_budg                1478
dtype: int64

In [22]:
answer_ls.append(1478)

# 9. Самый прибыльный фильм в 2008 году?
Варианты ответов:
1. Madagascar: Escape 2 Africa	tt0479952
2. Iron Man	tt0371746
3. Kung Fu Panda	tt0441773
4. The Dark Knight	tt0468569
5. Mamma Mia!	tt0795421

In [23]:
data_2008=data[data.release_date.str.contains('2008')]
data_2008[data_2008.revenue==data_2008.revenue.max()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,rev_budg
600,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8432,8.1,2008,816921825

In [24]:
answer_ls.append('The Dark Knight tt0468569')

# 10. Самый убыточный фильм за период с 2012 по 2014 (включительно)?
Варианты ответов:
1. Winter's Tale	tt1837709
2. Stolen	tt1656186
3. Broken City	tt1235522
4. Upside Down	tt1374992
5. The Lone Ranger	tt1210819

In [25]:
a9=data[data.release_date.str.contains('2012|2013|2014')]
a9[a9.rev_budg==a9.rev_budg.min()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,rev_budg
1246,tt1210819,1.21451,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,1607,6.0,2013,-165710090

In [26]:
answer_ls.append('The Lone Ranger tt1210819')

# 11. Какого жанра фильмов больше всего?
Варианты ответов:
1. Action
2. Adventure
3. Drama
4. Comedy
5. Thriller

In [27]:
import collections
gen=[]
for g in data.genres:
    str_g=g.split('|')
    for i in str_g:
        gen.append(i)
c = collections.Counter()
for g in gen:
    c[g] += 1
c.most_common(1)

[('Drama', 782)]

In [28]:
answer_ls.append('Drama')

# 12. Какого жанра среди прибыльных фильмов больше всего?
Варианты ответов:
1. Drama
2. Comedy
3. Action
4. Thriller
5. Adventure

In [29]:
import collections
gen=[]
for g in data[data.revenue>data.budget].genres:
    str_g=g.split('|')
    for i in str_g:
        gen.append(i)
c = collections.Counter()
for g in gen:
    c[g] += 1
c.most_common(1)

[('Drama', 560)]

In [30]:
answer_ls.append('Drama')

# 13. Кто из режиссеров снял больше всего фильмов?
Варианты ответов:
1. Steven Spielberg
2. Ridley Scott 
3. Steven Soderbergh
4. Christopher Nolan
5. Clint Eastwood

In [31]:
import collections
dirs=[]
for d in data.director:
    str_d=d.split('|')
    for i in str_d:
        dirs.append(i)
c = collections.Counter()
for d in dirs:
    c[d] += 1
c.most_common(1)

[('Steven Soderbergh', 13)]

In [32]:
answer_ls.append('Steven Soderbergh')

# 14. Кто из режиссеров снял больше всего Прибыльных фильмов?
Варианты ответов:
1. Steven Soderbergh
2. Clint Eastwood
3. Steven Spielberg
4. Ridley Scott
5. Christopher Nolan

In [33]:
import collections
dirs=[]
for d in data[data.revenue>data.budget].director:
    str_d=d.split('|')
    for i in str_d:
        dirs.append(i)
c = collections.Counter()
for d in dirs:
    c[d] += 1
c.most_common(1)

[('Ridley Scott', 12)]

In [34]:
answer_ls.append('Ridley Scott')

# 15. Кто из режиссеров принес больше всего прибыли?
Варианты ответов:
1. Steven Spielberg
2. Christopher Nolan
3. David Yates
4. James Cameron
5. Peter Jackson

In [35]:
dirs=[]
for d in data.director:
    str_d=d.split('|')
    for i in str_d:
        dirs.append(i)
set_dirs=set(dirs)
len(set_dirs)
sum_for_dir={}
for dir in set_dirs:
    sum_for_dir[dir]=sum(data.rev_budg[data.director==dir])
max(sum_for_dir, key=sum_for_dir.get)#thanks leo022 from stackoverflow.com

'Peter Jackson'

In [36]:
answer_ls.append('Peter Jackson')

# 16. Какой актер принес больше всего прибыли?
Варианты ответов:
1. Emma Watson
2. Johnny Depp
3. Michelle Rodriguez
4. Orlando Bloom
5. Rupert Grint

In [37]:
actors=[]
for actor in data.cast:
    str_actor=actor.split('|')
    for i in str_actor:
        actors.append(i)
set_actors=set(actors)
sum_for_actor={}
for a in set_actors:
    sum_for_actor[a]=sum(data.rev_budg[data.cast.str.contains(a)])
max(sum_for_actor, key=sum_for_actor.get)#thanks leo022 from stackoverflow.com

'Emma Watson'

In [38]:
answer_ls.append('Emma Watson')

# 17. Какой актер принес меньше всего прибыли в 2012 году?
Варианты ответов:
1. Nicolas Cage
2. Danny Huston
3. Kirsten Dunst
4. Jim Sturgess
5. Sami Gayle

In [39]:
movies_2012=data[data.release_year==2012]
actors=[]
for actor in data.cast:
    str_actor=actor.split('|')
    for i in str_actor:
        actors.append(i)
set_actors=set(actors)
actors_value={}
for actor in set_actors:
    actors_value[actor]=sum(movies_2012.rev_budg[movies_2012.cast.str.contains(actor)])
min(actors_value, key=actors_value.get)

'Kirsten Dunst'

In [40]:
answer_ls.append('Kirsten Dunst')

# 18. Какой актер снялся в большем количестве высокобюджетных фильмов? (в фильмах где бюджет выше среднего по данной выборке)
Варианты ответов:
1. Tom Cruise
2. Mark Wahlberg 
3. Matt Damon
4. Angelina Jolie
5. Adam Sandler

In [41]:
ab_budget=data[data.budget>data.budget.mean()]
actors=[]
for actor in ab_budget.cast:
    str_actor=actor.split('|')
    for i in str_actor:
        actors.append(i)
import collections
c = collections.Counter()
for a in actors:
    c[a] += 1
c.most_common(1)

[('Matt Damon', 18)]

In [42]:
answer_ls.append('Matt Damon')

# 19. В фильмах какого жанра больше всего снимался Nicolas Cage?  
Варианты ответа:
1. Drama
2. Action
3. Thriller
4. Adventure
5. Crime

In [43]:
nc_movies=data[data.cast.str.contains('Nicolas Cage')]
genres=[]
for g in nc_movies.genres:
    str_gnrs=g.split('|')
    for i in str_gnrs:
        genres.append(i)
c = collections.Counter()
for j in genres:
    c[j] += 1
c.most_common(1)

[('Action', 17)]

In [44]:
answer_ls.append('Action')

# 20. Какая студия сняла больше всего фильмов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros
5. Twentieth Century Fox Film Corporation

In [45]:
comps=[]
for company in data.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
import collections
c = collections.Counter()
for company in comps:
    c[company] += 1
c.most_common(1)

[('Universal Pictures', 173)]

In [46]:
answer_ls.append('Universal Pictures')

# 21. Какая студия сняла больше всего фильмов в 2015 году?
Варианты ответа:
1. Universal Pictures
2. Paramount Pictures
3. Columbia Pictures
4. Warner Bros

5. Twentieth Century Fox Film Corporation

In [47]:
comps=[]
movies_2015=data[data.release_year==2015]
for company in movies_2015.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
import collections
c = collections.Counter()
for company in comps:
    c[company] += 1
c.most_common(1)

[('Warner Bros.', 12)]

In [48]:
answer_ls.append('Warner Bros')

# 22. Какая студия заработала больше всего денег в жанре комедий за все время?
Варианты ответа:
1. Warner Bros
2. Universal Pictures (Universal)
3. Columbia Pictures
4. Paramount Pictures
5. Walt Disney

In [49]:
comps=[]
comedies=data[data.genres.str.contains('Comedy')]
for company in comedies.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
comp_rev={}
for i in comps:
    comp_rev[i]=comedies[comedies.production_companies.str.contains(i)].rev_budg.sum()
max(comp_rev, key=comp_rev.get)

C:\Users\803513\Anaconda3\lib\site-packages\pandas\core\strings.py:1843: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

'Universal'

In [50]:
answer_ls.append('Universal Pictures (Universal)')

# 23. Какая студия заработала больше всего денег в 2012 году?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Columbia Pictures
4. Paramount Pictures
5. Lucasfilm

In [51]:
movies_2012=data[data.release_year==2012]
for company in movies_2012.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
set_comps=set(comps)
comp_rev={}
for i in set_comps:
    comp_rev[i]=movies_2012[movies_2012.production_companies.str.contains(i)]['rev_budg'].sum()
max(comp_rev, key=comp_rev.get)

'Columbia Pictures'

In [52]:
answer_ls.append('Columbia Pictures')

# 24. Самый убыточный фильм от Paramount Pictures
Варианты ответа:

1. K-19: The Widowmaker tt0267626
2. Next tt0435705
3. Twisted tt0315297
4. The Love Guru tt0811138
5. The Fighter tt0964517

In [53]:
pp_movies=data[data.production_companies.str.contains('Paramount Pictures')]
pp_movies[pp_movies.rev_budg==pp_movies.rev_budg.min()]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,rev_budg
926,tt0267626,0.72233,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures|Intermedia Films|National G...,7/19/2002,146,6.0,2002,-64831034

In [54]:
answer_ls.append('K-19: The Widowmaker tt0267626')

# 25. Какой Самый прибыльный год (заработали больше всего)?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2002
5. 2015

In [55]:
years=data.release_year.unique()
y_rev={}
for year in years:
    y_rev[year]=data[data.release_year==year]['rev_budg'].sum()
max(y_rev, key=y_rev.get)

2015

In [56]:
answer_ls.append(2015)

# 26. Какой Самый прибыльный год для студии Warner Bros?
Варианты ответа:
1. 2014
2. 2008
3. 2012
4. 2010
5. 2015

In [57]:
wb=data[data.production_companies.str.contains('Warner Bros')]
years=data.release_year.unique()
y_rev={}
for y in years:
    y_rev[y]=wb[wb.release_year==y].rev_budg.sum()
max(y_rev, key=y_rev.get)

2014

In [58]:
answer_ls.append(2014)

# 27. В каком месяце за все годы суммарно вышло больше всего фильмов?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [59]:
#data[data.release_date.str.startswith('5/')].count()
months=[]
for m in data.release_date:
    months.append(m[:2])
import collections
c = collections.Counter()
for m in months:
    c[m]+=1
c.most_common(1)

[('9/', 227)]

In [60]:
answer_ls.append('Сентябрь')

# 28. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)
Варианты ответа:
1. 345
2. 450
3. 478
4. 523
5. 381

In [61]:
mo=['6/','7/','8/']
cnt_mo=[]
for m in mo:
    cnt_mo.append(data[data.release_date.str.startswith(m)].count())
sum(cnt_mo)

imdb_id                 450
popularity              450
budget                  450
revenue                 450
original_title          450
cast                    450
director                450
tagline                 450
overview                450
runtime                 450
genres                  450
production_companies    450
release_date            450
vote_count              450
vote_average            450
release_year            450
rev_budg                450
dtype: int64

In [62]:
answer_ls.append(450)

# 29. Какой режисер выпускает (суммарно по годам) больше всего фильмов зимой?
Варианты ответов:
1. Steven Soderbergh
2. Christopher Nolan
3. Clint Eastwood
4. Ridley Scott
5. Peter Jackson

In [63]:
#winter movies
winter_movies=[]
for w in ['1/','2/','12/']:
    winter_movies.append(data[data.release_date.str.startswith(w)])
win_mov = pd.concat(winter_movies) 
dirs=[]
for d in win_mov.director:
    str_d=d.split('|')
    for i in str_d:
        dirs.append(i)
import collections
c = collections.Counter()
for i in dirs:
    c[i]+=1
c.most_common(1)

[('Peter Jackson', 7)]

In [64]:
answer_ls.append('Peter Jackson')

# 30. Какой месяц чаще всего по годам самый прибыльный?
Варианты ответа:
1. Январь
2. Июнь
3. Декабрь
4. Сентябрь
5. Май

In [66]:
months=[]
for m in data.release_date:
    months.append(m[:2])
set_months=set(months)
years=[]
for y in data.release_year:
    years.append(y)
set_years=set(years)
m_rev={}
for m in set_months:
    for y in set_years:
        m_rev[m]=data[(data.release_year==y)&data.release_date.str.startswith(m)].revenue.sum()
max(m_rev, key=m_rev.get)

'6/'

In [67]:
answer_ls.append('Июнь')

# 31. Названия фильмов какой студии в среднем самые длинные по количеству символов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [74]:
for company in data.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
set_comps=set(comps)
comp_len={}
data['title_len']=data.apply(lambda row: len(row.original_title), axis = 1)
for comp in set_comps:
    comp_len[comp]=data[data.production_companies.str.contains(comp)].title_len.mean()
max(comp_len, key=comp_len.get)

'Four By Two Productions'

In [73]:
answer_ls.append('Four By Two Productions')

# 32. Названия фильмов какой студии в среднем самые длинные по количеству слов?
Варианты ответа:
1. Universal Pictures (Universal)
2. Warner Bros
3. Jim Henson Company, The
4. Paramount Pictures
5. Four By Two Productions

In [85]:
import re
for company in data.production_companies:
    str_comps=company.split('|')
    for i in str_comps:
        comps.append(i)
set_comps=set(comps)
comp_words={}
data['title_words']=data.apply(lambda row: len(re.findall(r'\w+', row.original_title)), axis = 1)
for comp in set_comps:
    comp_words[comp]=data[data.production_companies.str.contains(comp)].title_words.mean()
max(comp_words, key=comp_words.get)

'Four By Two Productions'

In [86]:
answer_ls.append('Four By Two Productions')

# 33. Сколько разных слов используется в названиях фильмов?(без учета регистра)
Варианты ответа:
1. 6540
2. 1002
3. 2461
4. 28304
5. 3432

In [87]:
data_words=[]
for i in data.original_title:
    i_low=i.lower()
    data_words.append(i_low.split())
data_words
d_w=[]
for k in data_words:
    for l in k:
        d_w.append(l)
len(set(d_w))

2461

In [88]:
answer_ls.append(2461)

# 34. Какие фильмы входят в 1 процент лучших по рейтингу?
Варианты ответа:
1. Inside Out, Gone Girl, 12 Years a Slave
2. BloodRayne, The Adventures of Rocky & Bullwinkle
3. The Lord of the Rings: The Return of the King
4. 300, Lucky Number Slevin

In [96]:
one_pcnt = data['vote_average'].value_counts(bins=10)
one_pcnt

(5.7, 6.18]      481
(6.18, 6.66]     470
(6.66, 7.14]     277
(5.22, 5.7]      261
(4.74, 5.22]     153
(7.14, 7.62]     144
(4.26, 4.74]      42
(7.62, 8.1]       41
(3.78, 4.26]      15
(3.294, 3.78]      6
Name: vote_average, dtype: int64

In [97]:
data.loc[(data['vote_average'] > one_pcnt.index[7].left) & (data['vote_average'] <= one_pcnt.index[7].right)]

,imdb_id,popularity,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,rev_budg,title_len,title_words
9,tt2096673,6.326804,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,3935,8.0,2015,678708609,10,2
28,tt1895587,4.062293,20000000,88346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,Tom McCarthy,Break the story. Break the silence.,The true story of how The Boston Globe uncover...,128,Drama|Thriller|History,Participant Media|Open Road Films|Anonymous Co...,11/6/2015,1559,7.8,2015,68346473,9,1
34,tt3170832,3.557846,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,1520,8.0,2015,29401758,4,1
38,tt1398426,3.202719,28000000,201634991,Straight Outta Compton,O'Shea Jackson Jr.|Corey Hawkins|Jason Mitchel...,F. Gary Gray,The Story of N.W.A.,"In 1987, five young men, using brutally honest...",147,Drama|Music,New Line Cinema|Universal Pictures|Legendary P...,8/13/2015,918,7.7,2015,173634991,22,3
118,tt0816692,24.949134,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,6498,8.0,2014,456752480,12,1
119,tt2015381,14.311205,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,5612,7.9,2014,603312399,23,4
124,tt2245084,8.691294,165000000,652105443,Big Hero 6,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,Don Hall|Chris Williams,From the creators of Wreck-it Ralph and Frozen,The special bond that develops between plus-si...,102,Adventure|Family|Animation|Action|Comedy,Walt Disney Pictures|Walt Disney Animation Stu...,10/24/2014,4185,7.8,2014,487105443,10,3
125,tt2084970,8.110711,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,3478,8.0,2014,219555708,18,3
128,tt2267998,6.438727,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,3720,7.9,2014,308330363,9,2
138,tt2278388,4.930820,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,2802,7.9,2014,144600318,24,4
143,tt1631867,3.990452,178000000,370541256,Edge of Tomorrow,Tom Cruise|Emily Blunt|Brendan Gleeson|Bill Pa...,Doug Liman,"Live, Die, Repeat",Major Bill Cage is an officer who has never se...,113,Action|Science Fiction,Village Roadshow Pictures|Warner Bros.|Viz Med...,5/27/2014,3267,7.7,2014,192541256,16,3
151,tt1646971,3.489106,145000000,609123048,How to Train Your Dragon 2,Jay Baruchel|Gerard Butler|Kristen Wiig|Jonah ...,Dean DeBlois,The training is over.,The thrilling second chapter of the epic How T...,102,Fantasy|Action|Adventure|Animation|Comedy,DreamWorks Animation|Mad Hatter Entertainment,6/12/2014,2152,7.7,2014,464123048,26,6
155,tt2980516,3.170271,15000000,121201940,The Theory of Everything,Eddie Redmayne|Felicity Jones|Harry Lloyd|Davi...,James Marsh,His Mind Changed Our World. Her Love Changed His.,A look at the relationship between the famous ...,123,Drama|Romance,Working Title Films,11/26/2014,1960,7.8,2014,106201940,24,4
177,tt2582846,2.293859,12000000,305151265,The Fault in Our Stars,Shailene Woodley|Ansel Elgort|Nat Wolff|Laura ...,Josh Boone,One Sick Love Story,Despite the tumor-shrinking medical miracle th...,125,Romance|Drama,Fox 2000 Pictures|Temple Hill Entertainment|TS...,5/16/2014,2389,7.8,2014,293151265,22,5
240,tt0361748,6.098027,70000000,319131050,Inglourious Basterds,Brad Pitt|MÃ©lanie Laurent|Christoph Waltz|Eli...,Quentin Tarantino,Once upon a time in Nazi occupied France...,"In Nazi-occupied France during World War II, a...",153,Drama|Action|Thriller|War,Universal Pictures|A Band Apart|Zehnte Babelsb...,8/18/2009,3969,7.7,2009,249131050,20,2
270,tt1028532,1.575231,16000000,47801389,Hachi: A Dog's Tale,Richard Gere|Joan Allen|Jason Alexander|Cary-H...,Lasse HallstrÃ¶m,"A true story of faith, devotion and undying love.",A drama based on the true story of a college p...,93,Drama|Family,Grand Army Entertainment|Scion Films|Inferno D...,6/13/2009,976,7.7,2009,31801389,19,5
283,tt0485947,1.260010,47000000,3547209,Mr. Nobody,Jared Leto|Diane Kruger|Linh Äan Pháº¡m|Sarah ...,Jaco Van Dormael,"Nothing is real, everything is possible.",Nemo Nobody leads an ordinary existence with h...,141,Science Fiction|Drama|Romance|Fantasy,Pan EuropÃ©enne Production|Virtual Films,9/11/2009,827,7.8,2009,-43452791,10,2
316,tt1187043,0.816681,9000000,70000000,3 Idiots,Aamir Khan|Kareena Kapoor|Madhavan|Sharman Jos...,Rajkumar Hirani,Don't BE A STUPID BE AN I.D.I.O.T.,In the tradition of â€œFerris Buellerâ€™s Day ...,170,Drama|Comedy|Romance,Vidhu Vinod Chopra Productions,12/23/2009,662,7.8,2009,61000000,8,2
370,tt1375666,9.363643,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,9767,7.9,2010,665500000,9,1
497,tt0120737,8.575419,93000000,871368364,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,One ring to rule them all,"Young hobbit Frodo Baggins, after inheriting a...",178,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/2001,6079,7.8,2001,778368364,49,10
600,tt0468569,8.466668,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8432,8.1,2008,816921825,15,3
723,tt1201607,5.711315,125000000,1327817822,Harry Potter and the Deathly Hallows: Part 2,Daniel Radcliffe|Rupert Grint|Emma Watson|Alan...,David Yates,It all ends here.,"Harry, Ron and Hermione continue their quest t...",130,Adventure|Family|Fantasy,Warner Bros.|Heyday Films|Moving Picture Compa...,7/7/2011,3750,7.7,2011,1202817822,44,8
864,tt0167261,8.095275,79000000,926287400,The Lord of the Rings: The Two Towers,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,A New Power Is Rising.,Frodo and Sam are trekking to Mordor to destro...,179,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/2002,5114,7.8,2002,847287400,37,8
873,tt0253474,2.364204,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,938,7.9,2002,85072577,11,2
974,tt1853728,5.944518,100000000,425368238,Django Unchained,Jamie Foxx|Christoph Waltz|Leonardo DiCaprio|K...,Quentin Tarantino,"Life, liberty and the pursuit of vengeance.","With the help of a German bounty hunter, a fre...",165,Drama|Western,Columbia Pictures|The Weinstein Company,12/25/2012,7375,7.7,2012,325368238,16,2
1082,tt0167260,7.122455,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,5636,7.9,2003,1024888979,45,10
1184,tt0993846,4.877927,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,4027,7.9,2013,292000694,23,5
1189,tt1798709,3.951582,23000000,47351251,Her,Joaquin Phoenix|Scarlett Johansson|Rooney Mara...,Spike Jonze,A Spike Jonze Love Story,"In the not so distant future, Theodore, a lone...",126,Romance|Science Fiction|Drama,Annapurna Pictures,12/18/2013,2422,7.8,2013,24351251,3,1
1192,tt2024544,3.625529,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,2241,7.9,2013,167000000,16,4
1203,tt1979320,2.119986,38000000,90247624,Rush,Daniel BrÃ¼hl|Chris Hemsworth|Olivia Wilde|Ale...,Ron Howard,Everyone's driven by something.,A biographical drama centered on the rivalry b...,123,Drama|Action,Revolution Films|Working Title Films|Cross Cre...,9/2/2013,1472,7.7,2013,52247624,4,1
1206,tt1392214,2.032167,46000000,122126687,Prisoners,Hugh Jackman|Jake Gyllenhaal|Paul Dano|Maria B...,Denis Villeneuve,Every moment matters.,When Keller Dover's daughter and her friend go...,153,Drama|Thriller|Crime,Alcon Entertainment|Madhouse Entertainment|8:3...,9/18/2013,1826,7.8,2013,76126687,9,1
1214,tt0790636,1.765514,5000000,55198285,Dallas Buyers Club,Matthew McConaughey|Jennifer Garner|Jared Leto...,Jean-Marc VallÃ©e,Sometimes it takes a hustler to change the world,Loosely based on the true-life tale of Ron Woo...,117,Drama|History,Universal Studios|Universal Pictures|Voltage P...,9/7/2013,1831,7.8,2013,50198285,18,3
1229,tt1535109,1.405720,55000000,95000000,Captain Phillips,Tom Hanks|Catherine Keener|Max Martini|Chris M...,Paul Greengrass,Out here survival is everything.,The true story of Captain Richard Phillips and...,134,Action|Drama|Thriller,Columbia Pictures,10/10/2013,1729,7.7,2013,40000000,16,2
1275,tt1924396,0.873688,13500000,19255873,La migliore offerta,Geoffrey Rush|Jim Sturgess|Sylvia Hoeks|Donald...,Giuseppe Tornatore,A Master of Possession. A Crime of Obsession,Virgil Oldman is a world renowned antiques exp...,124,Drama|Romance|Crime|Mystery,Paco Cinematografica|Warner Bros.|Regione Lazi...,1/1/2013,389,7.7,2013,5755873,19,3
1443,tt0407887,2.819750,90000000,289847354,The Departed,Leonardo DiCaprio|Matt Damon|Jack Nicholson|Ma...,Martin Scorsese,Lies. Betrayal. Sacrifice. How far will you ta...,"To take down South Boston's Irish Mafia, the p...",151,Drama|Thriller|Crime,Vertigo Entertainment|Media Asia Films|Warner ...,10/5/2006,2635,7.7,2006,199847354,12,2
1445,tt0482571,2.582095,40000000,109676311,The Prestige,Hugh Jackman|Christian Bale|Michael Caine|Scar...,Christopher Nolan,Are You Watching Closely?,A mysterious story of two magicians whose inte...,130,Drama|Mystery|Thriller,Touchstone Pictures|Syncopy,10/19/2006,2519,7.8,2006,69676311,12,2
1564,tt0338013,3.863377,20000000,72258126,Eternal Sunshine of the Spotless Mind,Jim Carrey|Kate Winslet|Elijah Wood|Mark Ruffa...,Michel Gondry,I already forget how I used to feel about you.,"Joel Barish, heartbroken that his girlfriend u...",108,Science Fiction|Drama|Romance,Anonymous Content|This Is That Productions|Foc...,3/19/2004,2012,7.8,2004,52258126,37,6
1682,tt0758758,2.194526,15000000,56255142,Into the Wild,Emile Hirsch|Marcia Gay Harden|William Hurt|Je...,Sean Penn,Into the heart. Into the soul.,"The true story of top student and athlete, Chr...",148,Adventure|Drama,Paramount Vantage|River Road Entertainment|Art...,9/11/2007,1768,7.7,2007,41255142,13,3
1689,tt0469494,2.042620,25000000,76181545,There Will Be Blood,Daniel Day-Lewis|Paul Dano|Dillon Freasier|Cia...,Paul Thomas Anderson,There Will Be Greed. There Will Be Vengeance.,"When ruthless oil prospector, Daniel Plainview...",158,Drama,Miramax Films|Ghoulardi Film Company|Paramount...,12/28/2007,830,7.8,2007,51181545,19,4
1800,tt0172495,4.271452,103000000,457640427,Gladiator,Russell Crowe|Joaquin Phoenix|Connie Nielsen|O...,Ridley Scott,A Hero Will Rise.,General Maximus' success in battle earns the f...,155,Action|Drama|Adventure,DreamWorks SKG|Universal Pictures|Scott Free P...,5/1/2000,3531,7.7,2000,354640427,9,1
1801,tt0209144,3.095625,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,2144,7.9,2000,30723096,7,1

In [98]:
answer_ls.append('Inside Out, Gone Girl, 12 Years a Slave')

# 35. Какие актеры чаще всего снимаются в одном фильме вместе
Варианты ответа:
1. Johnny Depp & Helena Bonham Carter
2. Hugh Jackman & Ian McKellen
3. Vin Diesel & Paul Walker
4. Adam Sandler & Kevin James
5. Daniel Radcliffe & Rupert Grint

In [100]:
duos=['Johnny Depp & Helena Bonham Carter','Hugh Jackman & Ian McKellen','Vin Diesel & Paul Walker','Adam Sandler & Kevin James',
      'Daniel Radcliffe & Rupert Grint']
duos_cnt={}
for i in duos:
    actor1,actor2=i.split(' & ')
    duos_cnt[i]=len(data[(data.cast.str.contains(actor1))&(data.cast.str.contains(actor2))])
max(duos_cnt, key=duos_cnt.get)

'Daniel Radcliffe & Rupert Grint'

In [101]:
answer_ls.append('Daniel Radcliffe & Rupert Grint')

# 36. У какого из режиссеров самый высокий процент фильмов со сборами выше бюджета? (5 баллов)101
Варианты ответа:
1. Quentin Tarantino
2. Steven Soderbergh
3. Robert Rodriguez
4. Christopher Nolan
5. Clint Eastwood

In [119]:
dirs=[]
for d in data.director:
    str_d=d.split('|')
    for i in str_d:
        dirs.append(i)
set_dirs=set(dirs)
dir_rev_budg={}
for d in set_dirs:
    dir_rev_budg[d]=len(data[(data.director.str.contains(d))&(data.revenue>data.budget)])/len(data[data.director.str.contains(d)])
#max(dir_rev_budg, key=dir_rev_budg.get) 
for i in dir_rev_budg.keys():
    if i in ['Quentin Tarantino','Steven Soderbergh','Robert Rodriguez','Christopher Nolan','Clint Eastwood']:
        print(i,dir_rev_budg[i])

Clint Eastwood 0.8333333333333334
Steven Soderbergh 0.7692307692307693
Christopher Nolan 1.0
Quentin Tarantino 0.8571428571428571
Robert Rodriguez 0.7272727272727273

In [120]:
answer_ls.append('Christopher Nolan')

# Submission

In [121]:
len(answer_ls)

36

In [122]:
pd.DataFrame({'Id':range(1,len(answer_ls)+1), 'Answer':answer_ls}, columns=['Id', 'Answer'])

    Id                                   Answer
0    1            The Warrior's Way (tt1032751)
1    2            Gods and Generals (tt0279111)
2    3                Winnie the Pooh tt1449283
3    4                                      110
4    5                                      106
5    6                         Avatar tt0499549
6    7              The Warrior's Way tt1032751
7    8                                     1478
8    9                The Dark Knight tt0468569
9   10                The Lone Ranger tt1210819
10  11                                    Drama
11  12                                    Drama
12  13                        Steven Soderbergh
13  14                             Ridley Scott
14  15                            Peter Jackson
15  16                              Emma Watson
16  17                            Kirsten Dunst
17  18                               Matt Damon
18  19                                   Action
19  20                       Universal Pictures
20  21                              Warner Bros
21  22           Universal Pictures (Universal)
22  23                        Columbia Pictures
23  24           K-19: The Widowmaker tt0267626
24  25                                     2015
25  26                                     2014
26  27                                 Сентябрь
27  28                                      450
28  29                            Peter Jackson
29  30                                     Июнь
30  31                  Four By Two Productions
31  32                  Four By Two Productions
32  33                                     2461
33  34  Inside Out, Gone Girl, 12 Years a Slave
34  35          Daniel Radcliffe & Rupert Grint
35  36                        Christopher Nolan